name: wear_plus_example
description: Demonstrates how to use the wear plugin.
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  wear_plus:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^10.1.0

flutter:
  uses-material-design: true
